@startuml
top to bottom direction
left to right direction
class Board {
    title String
    collaborators Array<User>
    tasks Array<Task>
    --
    addColaborator(<User>)
    removeColaborator(<User>)
}
class User {
    id Integer
    name String
    avatar String
    --
    addTask(<Task>)
    deleteTask(<Task>)
    createBoard(<Board>)
    deleteBoard(<Board>)
}
cloud {
    object UserAccess {
        user key
        board key
        accessLevel Integer
    }
}
class Task {
    name String
    users Array<User>
    state Integer
}

Board --{ UserAccess
User --{ UserAccess
Board --{ Task


@enduml