@startuml
top to bottom direction
left to right direction
object Board {
    title String
    collaborators Array<User>
    tasks Array<Task>
}
object User {
    id Integer
    name String
    avatar String
}
cloud {
    object UserAccess {
        user key
        board key
        accessLevel Integer
    }
}
object Task {
    name String
    users Array<User>
    state Integer
}

Board --{ UserAccess
User --{ UserAccess
Board --{ Task


@enduml